type Like {
    code: Int!
},
type Story {
    body: String
    public: Boolean
    likes: [Like!]!
},
type Cat {
    id: Int!
    name: String!
    age: Int!
},
type Query {
    cat(id: Int!) : Cat!
    stories(): [Story!]!
}